CREATE USER ${DSPACE_DB_USER} IDENTIFIED BY ${DSPACE_DB_USER_PASSWORD};
GRANT CONNECT TO ${DSPACE_DB_USER};
GRANT CREATE TABLE TO ${DSPACE_DB_USER};
GRANT CREATE SEQUENCE TO ${DSPACE_DB_USER};
GRANT CREATE VIEW TO ${DSPACE_DB_USER};
GRANT CREATE MATERIALIZED VIEW TO ${DSPACE_DB_USER};
GRANT CREATE PROCEDURE TO ${DSPACE_DB_USER};
GRANT UNLIMITED TABLESPACE TO ${DSPACE_DB_USER};

EXIT;
